In [8]:
import pandas as pd

df = pd.read_csv("very_messy_dataset_2500_rows.csv")
df.head(10)

,id,name,age,city,country,department,salary,email,join_date,score
0,0.0,Ali,NaN,lyon,france,Finance,2200,NaN,2023-01-05,NaN
1,NaN,Sara,29,marseille,France,IT,2000,test@yahoo.com,05/01/2023,90
2,2.0,Omar,23,NaN,NaN,NaN,4000,test@yahoo.com,2023/01/05,100
3,3.0,mohamed,twenty,PARIS,NaN,SALES,3500,contact@outlook.com,05/01/2023,40
4,490.0,Sara,21,marseille,France,it,3500,NaN,Jan 5 2023,fifty
5,NaN,Nadia,28,paris,FRA,Sales,3000€,contact@outlook.com,NaN,NaN
6,316.0,Amina,23,paris,France,Finance,999999,contact@outlook.com,2023-01-05,40
7,7.0,Karim,24,LILLE,NaN,it,2200,contact@outlook.com,Jan 5 2023,40
8,343.0,SARA,30,NaN,France,HR,3000€,NaN,05/01/2023,30
9,236.0,Youssef,30,Lille,france,it,999999,user@gmail.com,05/01/2023,10

In [5]:
text_columns = ["city", "name", "country", "department"]

for col in text_columns:
    df[col] = df[col].str.lower().str.strip()

df.head(5)

,id,name,age,city,country,department,salary,email,join_date,score
0,0.0,ali,NaN,lyon,france,finance,2200,NaN,2023-01-05,NaN
1,NaN,sara,29,marseille,france,it,2000,test@yahoo.com,05/01/2023,90
2,2.0,omar,23,NaN,NaN,NaN,4000,test@yahoo.com,2023/01/05,100
3,3.0,mohamed,twenty,paris,NaN,sales,3500,contact@outlook.com,05/01/2023,40
4,490.0,sara,21,marseille,france,it,3500,NaN,Jan 5 2023,fifty

In [8]:
df["salary"] = df["salary"].str.replace("€", "", regex=False)
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")

df["salary"].head(10)

0      2200.0
1      2000.0
2      4000.0
3      3500.0
4      3500.0
5      3000.0
6    999999.0
7      2200.0
8      3000.0
9    999999.0
Name: salary, dtype: float64

In [26]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["age"].head(10)

0     NaN
1    29.0
2    23.0
3     NaN
4    21.0
5    28.0
6    23.0
7    24.0
8    30.0
9    30.0
Name: age, dtype: float64

In [11]:
print(f"NaT %: {df['join_date'].isnull().mean() * 100:.2f}%")

NaT %: 85.56%

In [8]:
df["join_date"] = pd.to_datetime(df["join_date"], errors="coerce")
df["join_date"].head(10)

0   2023-01-05
1          NaT
2          NaT
3          NaT
4          NaT
5          NaT
6   2023-01-05
7          NaT
8          NaT
9          NaT
Name: join_date, dtype: datetime64[ns]

In [9]:
df = df.drop(columns=["join_date"])
print(df.columns)

Index(['id', 'name', 'age', 'city', 'country', 'department', 'salary', 'email',
       'score'],
      dtype='object')

In [11]:
df["score"] = pd.to_numeric(df["score"], errors="coerce")
df["score"].head(10)

0      NaN
1     90.0
2    100.0
3     40.0
4      NaN
5      NaN
6     40.0
7     40.0
8     30.0
9     10.0
Name: score, dtype: float64

In [19]:
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)

IQR = Q3 - Q1

upper_limit = Q3 + 1.5 * IQR
print(f"the upper limit is: {upper_limit}")

df = df[df["salary"] <= upper_limit]
print(df["salary"].max())

df = df[df["salary"] > 0]

print("befor:", df.shape[0])
df = df[df["salary"] <= upper_limit]
print("after", df.shape[0])

the upper limit is: 4500.0
4000.0
befor: 1659
after 1659

In [20]:
print(df["salary"].describe())

count    1659.000000
mean     2729.113924
std       708.216383
min      1800.000000
25%      2000.000000
50%      2500.000000
75%      3000.000000
max      4000.000000
Name: salary, dtype: float64

In [22]:
print(df["salary"].skew())

0.3304238395614663