In [2]:
import sqlite3
import pandas as pd

df = pd.read_csv("cleaned_employees_data.csv")
conn = sqlite3.connect("employees.db")
df.to_sql("employees", conn, if_exists="replace", index=False)

print("Database created ")

Database created

In [8]:
query ="""
SELECT *
FROM employees
WHERE department = "IT"
LIMIT 5;
"""

result = pd.read_sql_query(query, conn)

display(result)

Empty DataFrame
Columns: [id, name, age, city, country, department, salary, email, score]
Index: []

In [11]:
query="""
SELECT *
FROM employees
WHERE salary >= 4000
LIMIT 5;
"""

result = pd.read_sql_query(query, conn)
display(result)

,id,name,age,city,country,department,salary,email,score
0,2.0,omar,23.0,unknown,unknown,unknown,4000.0,test@yahoo.com,100.0
1,26.0,sara,30.0,marseille,fr,sales,4000.0,invalid-email,50.0
2,44.0,unknown,25.0,None,unknown,hr,4000.0,test@yahoo.com,50.0
3,167.0,sara,24.0,lille,france,finance,4000.0,unknown,50.0
4,unknown,lina,25.0,lille,unknown,unknown,4000.0,unknown,30.0

In [5]:
query = """
SELECT name, salary
FROM employees
WHERE department = "sales"
"""
result = pd.read_sql_query(query, conn)
display(result)

        name  salary
0    mohamed  3500.0
1      nadia  3000.0
2       sara  4000.0
3     fatima  2200.0
4     fatima  3500.0
..       ...     ...
367     sara  3000.0
368    amina  2000.0
369   fatima  2500.0
370  unknown  2000.0
371  unknown  1800.0

[372 rows x 2 columns]

In [9]:
query= """
SELECT name, salary
FROM employees
WHERE department = "sales"
ORDER BY salary DESC
LIMIT 5
"""
result = pd.read_sql_query(query, conn)
display(result)

      name  salary
0     sara  4000.0
1  unknown  4000.0
2      ali  4000.0
3     omar  4000.0
4    amina  4000.0

In [10]:
query= """
SELECT AVG(salary)
FROM employees
WHERE department = "IT"
"""
result = pd.read_sql_query(query, conn)
display(result)

  AVG(salary)
0        None