In [4]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\roaming\python\python313\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('cleaned_employees_data.csv')

df.head(3)

,id,name,age,city,country,department,salary,email,score
0,0.0,ali,25.0,lyon,france,finance,2200.0,unknown,50.0
1,unknown,sara,29.0,marseille,france,it,2000.0,test@yahoo.com,90.0
2,2.0,omar,23.0,unknown,unknown,unknown,4000.0,test@yahoo.com,100.0

In [3]:
df = df.drop(['id', 'email', 'name' ], axis=1, errors='ignore')
df.head(3)

    age       city  country department  salary  score
0  25.0       lyon   france    finance  2200.0   50.0
1  29.0  marseille   france         it  2000.0   90.0
2  23.0    unknown  unknown    unknown  4000.0  100.0

In [4]:
df.isnull().sum()

age            0
city          35
country        0
department    28
salary         0
score          0
dtype: int64

In [9]:
import numpy as np
df.replace('unknown', np.nan, inplace=True)
df.head(3)

    age       city country department  salary  score
0  25.0       lyon  france    finance  2200.0   50.0
1  29.0  marseille  france         it  2000.0   90.0
2  23.0        NaN     NaN        NaN  4000.0  100.0

In [10]:
df.isnull().sum()

age             0
city          270
country       529
department    340
salary          0
score           0
dtype: int64

In [5]:
print((df.isnull().sum()/ len(df))* 100)

age           0.000000
city          2.265372
country       0.000000
department    1.812298
salary        0.000000
score         0.000000
dtype: float64

In [6]:
df['country'] = df['country'].fillna("others")
df['city'] = df['city'].fillna('others')
df['department'] = df['department'].fillna(df['department'].mode()[0])
df.head(3)

    age       city  country department  salary  score
0  25.0       lyon   france    finance  2200.0   50.0
1  29.0  marseille   france         it  2000.0   90.0
2  23.0    unknown  unknown    unknown  4000.0  100.0

In [7]:
df.isnull().sum()

age           0
city          0
country       0
department    0
salary        0
score         0
dtype: int64

In [8]:
df_final = pd.get_dummies(df, drop_first=True)
df_final.head()

,age,salary,score,city_lyon,city_marseille,city_others,city_paris,city_unknown,country_fra,country_france,country_unknown,department_hr,department_it,department_marketing,department_sales,department_unknown
0,25.0,2200.0,50.0,True,False,False,False,False,False,True,False,False,False,False,False,False
1,29.0,2000.0,90.0,False,True,False,False,False,False,True,False,False,True,False,False,False
2,23.0,4000.0,100.0,False,False,False,False,True,False,False,True,False,False,False,False,True
3,25.0,3500.0,40.0,False,False,False,True,False,False,False,True,False,False,False,True,False
4,21.0,3500.0,50.0,False,True,False,False,False,False,True,False,False,True,False,False,False

In [9]:
df['country'] = df['country'].replace(['fr','fra'], 'france')
df_final = pd.get_dummies(df)
df_final.head()

,age,salary,score,city_lille,city_lyon,city_marseille,city_others,city_paris,city_unknown,country_france,country_unknown,department_finance,department_hr,department_it,department_marketing,department_sales,department_unknown
0,25.0,2200.0,50.0,False,True,False,False,False,False,True,False,True,False,False,False,False,False
1,29.0,2000.0,90.0,False,False,True,False,False,False,True,False,False,False,True,False,False,False
2,23.0,4000.0,100.0,False,False,False,False,False,True,False,True,False,False,False,False,False,True
3,25.0,3500.0,40.0,False,False,False,False,True,False,False,True,False,False,False,False,True,False
4,21.0,3500.0,50.0,False,False,True,False,False,False,True,False,False,False,True,False,False,False

In [10]:
X = df_final.drop(columns=['salary'])

y = df_final['salary']

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [17]:
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred)

[2709.84374128 2677.47869517 2682.71143007 2702.47635283 2810.58962286
 2702.52935246 2596.50169421 2820.37800432 2752.88726332 2672.75892049
 2743.38355409 2624.61737704 2763.32556181 2732.61246953 2715.02893647
 2661.31492537 2695.75698012 2696.31798411 2717.37450789 2679.43410692
 2649.16212567 2708.35045094 2651.52997906 2842.25460328 2682.18142264
 2723.5649972  2755.60222557 2648.20233905 2715.02893647 2726.1895462
 2624.61737704 2724.21935621 2843.239529   2778.48935129 2765.86475771
 2682.18142264 2763.48968994 2636.07693793 2673.60531912 2663.81693766
 2712.38291182 2774.6504031  2646.08634247 2733.03566885 2768.17228101
 2817.31297878 2719.39095855 2579.69370202 2723.24728739 2877.12806988
 2724.94008465 2835.56714412 2717.25939618 2649.80634806 2644.17252213
 2751.23734431 2712.21224442 2647.77913973 2741.87216217 2693.48188013
 2726.97799032 2846.20192421 2680.28050555 2738.50733854 2693.86200661
 2844.93232626 2723.14179788 2858.98009948 2852.88938337 2770.79335606
 2703.00616568 2630.54794823 2754.71837452 2795.27225169 2816.16108499
 2591.81910314 2717.8251058  2765.01835908 2816.41358052 2737.15386891
 2616.07845713 2670.61552531 2707.36552522 2679.59321032 2756.34323812
 2779.33574993 2685.12220002 2716.63073958 2811.43602149 2776.01535865
 2663.20989888 2715.04621369 2666.07146133 2735.07357452 2856.72557581
 2749.07120728 2668.98004806 2640.759529   2689.94461181 2734.97094419
 2664.4042651  2622.02916472 2702.90353536 2702.84706228 2724.84471653
 2727.27708367 2819.00577605 2768.04543992 2780.08330648 2839.89839758
 2685.91212557 2709.51722398 2642.36353801 2695.1746774  2747.50664138
 2773.38080515 2766.22695184 2715.9027337  2721.87219993 2779.59482111
 2693.56723324 2707.92725162 2718.24830512 2669.67807893 2892.44544105
 2712.21224442 2614.30030676 2841.16799553 2586.29011343 2705.34318533
 2682.05865592 2736.32589525 2711.31284615 2737.7720684  2618.98289783
 2719.94110238 2748.6808712  2778.28441929 2680.11923454 2703.85256431
 2676.74122119 2622.02916472 2690.49208632 2650.68358043 2642.50134269
 2660.557315   2736.83440886 2722.94975826 2668.43408202 2708.00534253
 2719.41109495 2688.95839246 2756.49957557 2758.91258837 2766.90268307
 2761.96756008 2829.78565889 2831.20085831 2753.87197589 2640.759529
 2676.52966622 2806.45865705 2676.31802187 2766.0032848  2700.28046778
 2663.98106579 2753.38084291 2753.22510953 2911.59900465 2692.29763529
 2703.27026159 2773.9603419  2748.54251846 2684.30811657 2719.39095855
 2676.54694343 2815.31468635 2599.40613491 2757.19239252 2693.48188013
 2676.74122119 2829.64055614 2739.68588874 2756.34599388 2739.56412596
 2629.04877544 2833.89994789 2718.69312226 2731.68135229 2796.96504896
 2765.01835908 2816.50619339 2769.27775083 2738.55460472 2760.5461568
 2661.0939023  2699.01086984 2729.72948384 2706.18958397 2735.0562973
 2617.29010056 2727.21190577 2607.1364743  2903.10761974 2807.30505568
 2671.00067651 2751.81698449 2653.21934118 2675.68326758 2694.48738217
 2703.10613346 2743.09888186 2791.14128588 2610.12626811 2811.43602149
 2677.35046381 2645.2507015  2725.8932914  2687.88241899 2809.36249733
 2723.14179788 2752.50694226 2666.52964041 2780.08330648 2840.24973519
 2704.96305886 2715.25851131 2760.12918669 2647.77913973 2690.91528564
 2846.51399503 2734.30526679 2730.28835312 2636.09855576 2719.09072054
 2686.42411315 2670.26034335 2678.43401846 2757.61559183 2672.05863012
 2735.65607182 2758.90983262 2699.09474151 2674.1746267  2668.55684874
 2717.25939618 2743.96541689 2636.50013725 2689.83710627 2828.93926025
 2772.48416264 2729.56535571 2726.554791   2774.20634918 2681.01863281
 2700.73453914 2757.19239252 2705.34318533 2693.65254754 2711.95971251
 2763.61404152 2692.90499099 2646.9327411  2628.45356948 2749.10407052
 2705.34318533 2751.95551158 2727.35831138 2716.36398113 2673.98034894
 2728.77627709 2711.02073738 2835.16954584 2617.71329988 2683.85260208
 2739.73888837 2731.64330418 2719.04170411 2695.3337808  2754.38357899
 2598.61769079 2812.35229114 2669.34592736 2670.26034335 2800.50646803
 2701.92188862 2735.99806406 2761.32069373 2833.87434685 2743.52208118
 2779.59482111 2703.3757511  2756.7691932  2757.61559183 2735.68167286
 2664.37866406 2687.22989302 2698.5290319  2686.87471106 2784.595122
 2717.77210617 2691.44111528 2685.27802457 2875.43527262 2780.36312884
 2603.24232735 2672.71075099 2761.0049746  2637.68094694]